
package com.acme.orders.api.integrations.lib.catalogue;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ECommerceWsService", targetNamespace = "http://acme.com/services/eCommerce/v1", wsdlLocation = "file:/C:/DEV/GIT/Java_Microservices/acme-orders/api/src/resources/ECommerceWs.wsdl")
public class ECommerceWsService
    extends Service
{

    private final static URL ECOMMERCEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECOMMERCEWSSERVICE_EXCEPTION;
    private final static QName ECOMMERCEWSSERVICE_QNAME = new QName("http://acme.com/services/eCommerce/v1", "ECommerceWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/DEV/GIT/Java_Microservices/acme-orders/api/src/resources/ECommerceWs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECOMMERCEWSSERVICE_WSDL_LOCATION = url;
        ECOMMERCEWSSERVICE_EXCEPTION = e;
    }

    public ECommerceWsService() {
        super(__getWsdlLocation(), ECOMMERCEWSSERVICE_QNAME);
    }

    public ECommerceWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECOMMERCEWSSERVICE_QNAME, features);
    }

    public ECommerceWsService(URL wsdlLocation) {
        super(wsdlLocation, ECOMMERCEWSSERVICE_QNAME);
    }

    public ECommerceWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECOMMERCEWSSERVICE_QNAME, features);
    }

    public ECommerceWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ECommerceWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ECommerce
     */
    @WebEndpoint(name = "ECommercePort")
    public ECommerce getECommercePort() {
        return super.getPort(new QName("http://acme.com/services/eCommerce/v1", "ECommercePort"), ECommerce.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ECommerce
     */
    @WebEndpoint(name = "ECommercePort")
    public ECommerce getECommercePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://acme.com/services/eCommerce/v1", "ECommercePort"), ECommerce.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECOMMERCEWSSERVICE_EXCEPTION!= null) {
            throw ECOMMERCEWSSERVICE_EXCEPTION;
        }
        return ECOMMERCEWSSERVICE_WSDL_LOCATION;
    }

}
