
package com.acme.orders.api.integrations.lib.catalogue;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ECommerce", targetNamespace = "http://acme.com/services/eCommerce/v1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ECommerce {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.acme.orders.api.integrations.lib.catalogue.RetrieveProductResponseMessage
     * @throws ECommerceErrorFault_Exception
     */
    @WebMethod(operationName = "RetrieveProduct", action = "http://acme.com/services/eCommerce/v1/RetrieveProduct")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RetrieveProduct", targetNamespace = "http://acme.com/services/eCommerce/v1", className = "com.acme.orders.api.integrations.lib.catalogue.RetrieveProduct")
    @ResponseWrapper(localName = "RetrieveProductResponse", targetNamespace = "http://acme.com/services/eCommerce/v1", className = "com.acme.orders.api.integrations.lib.catalogue.RetrieveProductResponse")
    public RetrieveProductResponseMessage retrieveProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        RetrieveProductRequestMessage arg0)
        throws ECommerceErrorFault_Exception
    ;

}
